name: Deploy Spb-Histmap Workflow

on:
  repository_dispatch:
    types:
      - deploy_spb_histmap
jobs:
  trigger:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github-Pages Repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout SPB-Histmap Repo
        uses: actions/checkout@v2
        with:
          repository: stepan-anokhin/spb-histmap
          path: spb-histmap/repo
      - name: Install SPB Histmap
        working-directory: spb-histmap/repo
        run: npm install
      - name: Build SPB Histmap
        working-directory: spb-histmap/repo
        run: npm run build
      - name: Copy Build Artifacts
        working-directory: spb-histmap
        run: cp repo/build/* .
      - name: Remove SPB Histmpa Repo
        working-directory: spb-histmap
        run: rm -rf repo
      - name: Change Parent URL
        working-directory: spb-histmap
        run: sed -ri 's/src="\/main.bundle.js"/src="\/spb-histmap\/main.bundle.js"/' index.html
      - name: Check State
        working-directory: spb-histmap
        run: |
          cat index.html
          ls -l .
